---
- name: Prepare all Kubernetes nodes
  hosts: k8s_all
  become: yes

  vars:
    k8s_version: "1.28.5"

  tasks:

    - name: Disable swap
      ansible.builtin.shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Load kernel modules
      ansible.builtin.shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
        modprobe overlay
        modprobe br_netfilter

    - name: Configure sysctl params
      ansible.builtin.shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward = 1
        EOF
        sysctl --system

    - name: Install required packages
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Install containerd (without starting)
      ansible.builtin.apt:
        name: containerd.io
        state: present
        update_cache: yes

    - name: Disable containerd auto-start before configuration
      ansible.builtin.systemd:
        name: containerd
        enabled: no
        state: stopped

    - name: Configure containerd
      ansible.builtin.copy:
        content: |
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'

    - name: Enable and start containerd safely
      ansible.builtin.systemd:
        name: containerd
        enabled: yes
        state: started

    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: kubernetes

    - name: Install kubeadm, kubelet, kubectl
      ansible.builtin.package:
        name:
          - "kubelet={{ k8s_version }}-00"
          - "kubeadm={{ k8s_version }}-00"
          - "kubectl={{ k8s_version }}-00"
        state: present
        allow_downgrade: yes
        update_cache: yes

    - name: Hold Kubernetes packages to prevent auto-update
      ansible.builtin.shell: |
        apt-mark hold kubelet kubeadm kubectl
